//
// Created by barto on 19.05.18.
//

#ifndef GRAPHREPRESENTATIONSANDALGORITHMSCOMPARISON_UNDIRECTEDGRAPH_H
#define GRAPHREPRESENTATIONSANDALGORITHMSCOMPARISON_UNDIRECTEDGRAPH_H


#include "Graph.h"

class UndirectedGraph : public Graph {

};


#endif //GRAPHREPRESENTATIONSANDALGORITHMSCOMPARISON_UNDIRECTEDGRAPH_H
